# Configuration file for protein-ligand molecular dynamics simulation
# Update the paths below to match your system

# Input files
holo_protein_pdb: "inputs/ERa.pdb"      # Crystal structure
new_ligand_file: "inputs/50-28-2_Estradiol.sdf"        # Your compound for holo simulation

# Force field and simulation parameters
force_field: "amber99sb-ildn"    # AMBER force field for protein
water_model: "tip3p"             # Water model
box_distance: 0.8                # Distance from protein to box edge (nm) - smaller for closer ligand

# Performance Settings (GPU-optimized threading handled automatically)

# Box geometry optimization
box_type: "dodecahedron"         # Rhombic dodecahedron for ~15% fewer water molecules

# Advanced settings (optimized for performance)
constraints: "h-bonds"           # Only H-bonds constrained (good for both CPU and GPU)
nstlist: 200                     # Optimized neighbor list update
nstcalcenergy: 1000              # Energy calculation frequency
dt: 0.002                        # 2 fs timestep

# Optional: Advanced parameters
ligand_charge: 0            # OPTIONAL: Net charge (auto-detected if not specified)
# temperature: 300                # Temperature in Kelvin
# pressure: 1.0                  # Pressure in bar
# ion_concentration: 0.15        # Salt concentration in M

# Simulation length parameters (TESTING - 1 ns each)
production_ns: 1                 # Production run length in nanoseconds
relaxation_ns: 1                 # Relaxation MD after steered MD (10-50 ns recommended)
em_steps: 5000                   # Energy minimization steps
nvt_steps: 5000                  # NVT equilibration steps (10 ps)
npt_steps: 5000                  # NPT equilibration steps (10 ps)

# Steered MD parameters
steered_md_pull_rate: 0.001      # Pull rate (nm/ps) - gentle pulling
steered_md_force_constant: 1000  # Force constant (kJ/mol/nm²) - strong restraint
steered_md_target_distance: 0.9  # Target distance as fraction of total distance
steered_md_max_time: 2           # Maximum simulation time (ns)
