# Configuration file for protein-ligand molecular dynamics simulation
# Update the paths below to match your system

# Input files
holo_protein_pdb: "inputs/ERa.pdb1"      # Crystal structure
# new_ligand_file: "inputs/ICI.sdf"       # Your compound (disabled for apo-only run)

# Ligand information
original_ligand_resn: "EST"              # Residue name of ligand in crystal structure (EST = estradiol)
target_chain: "A"                        # Which protein chain to use (A, B, C, etc. - reduces system size)

# Force field and simulation parameters
force_field: "amber99sb-ildn"    # AMBER force field for protein
water_model: "tip3p"             # Water model
box_distance: 1.2                # Distance from protein to box edge (nm)

# Performance Settings (GPU-optimized threading handled automatically)

# Box geometry optimization
box_type: "dodecahedron"         # Rhombic dodecahedron for ~15% fewer water molecules

# Advanced settings (optimized for performance)
constraints: "h-bonds"           # Only H-bonds constrained (good for both CPU and GPU)
nstlist: 200                     # Optimized neighbor list update
nstcalcenergy: 1000              # Energy calculation frequency
dt: 0.002                        # 2 fs timestep

# Optional: Advanced parameters
ligand_charge: 0            # OPTIONAL: Net charge (auto-detected if not specified)
# temperature: 300                # Temperature in Kelvin
# pressure: 1.0                  # Pressure in bar
# ion_concentration: 0.15        # Salt concentration in M

# Simulation length parameters
production_ns: 100              # Production run length in nanoseconds
em_steps: 50000                  # Energy minimization steps
nvt_steps: 50000                 # NVT equilibration steps (100 ps)
npt_steps: 50000                 # NPT equilibration steps (100 ps)
