name: md-pipeline
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  # Core Python
  - python=3.11
  - pip

  # CUDA support
  - cudatoolkit=11.8

  # Compilers (needed for some conda builds)
  - compilers
  - gcc_linux-64
  - gxx_linux-64

  # MPI
  - openmpi
  - mpi4py  # install via conda to avoid pip compilation issues

  # Molecular Dynamics Tools
  - gromacs>=2021
  - pymol-open-source
  - ambertools>=22
  - openbabel

  # Python packages for molecular work
  - numpy
  - scipy
  - matplotlib
  - pandas
  - rdkit
  - mdanalysis
  - pdbfixer
  - parmed

  # Workflow management
  - snakemake-minimal>=7.0

  # System utilities
  - wget
  - curl

  # Java for OpenBabel / visualization
  - openjdk=11

  # Pip packages
  - pip:
      - py3Dmol
      - acpype
      - git+https://github.com/Valdes-Tresanco-MS/gmx_MMPBSA.git
