name: md-pipeline
channels:
  - conda-forge
  - bioconda
dependencies:
  # Core Python
  - python=3.10
  - pip
  
  # CUDA support (install first to resolve dependencies)  
  - cudatoolkit=11.8
  
  # Molecular Dynamics Tools (EXPLICIT CUDA build - try multiple options)
  #- gromacs=2023.3=nompi_cuda_ha81c2ac_1  # Stable CUDA build
  - gromacs >=2021
  - pymol-open-source
  - ambertools >=22
  - openbabel
  
  # Python packages for molecular work
  - rdkit
  - mdanalysis
  - numpy
  - scipy
  - matplotlib
  - pandas
  - pdbfixer
  - parmed
  
  # Workflow management
  - snakemake-minimal >=7.0
  
  # System utilities
  - wget
  - curl
  
  # GPU monitoring and diagnostics  
  - gpustat           # Monitor GPU usage
  
  # Additional tools via pip
  - pip:
    - acpype
    - py3Dmol         # For 3D molecular visualization 

  - openbabel 
  - mdanalysis
  - openjdk=11
  
  # System dependencies (install via apt: sudo apt install mono-complete)
  # Mono is required for running Mole2.5 on Linux systems
  # Note: This is a system-level dependency that cannot be installed via conda
  # Install manually: sudo apt update && sudo apt install mono-complete -y 