name: md-pipeline
channels:
  - conda-forge
  - bioconda
  - ambermd
  - schrodinger
dependencies:
  # Core Python
  - python=3.10
  - pip
  
  # CUDA support (install first to resolve dependencies)  
  - cudatoolkit=11.8
  
  # Molecular Dynamics Tools (EXPLICIT CUDA build - try multiple options)
  - gromacs=2023.3=nompi_cuda_ha81c2ac_1  # Stable CUDA build
  - pymol-open-source
  - ambertools >=22
  - openbabel
  
  # Python packages for molecular work
  - rdkit
  - mdanalysis
  - numpy
  - scipy
  - matplotlib
  - pandas
  - pdbfixer
  - parmed
  
  # Workflow management
  - snakemake-minimal >=7.0
  
  # System utilities
  - wget
  - curl
  
  # GPU monitoring and diagnostics  
  - gpustat           # Monitor GPU usage
  
  # Additional tools via pip
  - pip:
    - acpype
    - py3Dmol         # For 3D molecular visualization 