name: md-pipeline
channels:
  - conda-forge
  - bioconda
  - ambermd
  - schrodinger
dependencies:
  # Core Python
  - python=3.10
  - pip
  
  # Molecular Dynamics Tools
  - gromacs >=2021
  - pymol-open-source
  - ambertools >=22
  - openbabel
  
  # Python packages for molecular work
  - rdkit
  - mdanalysis
  - numpy
  - scipy
  - matplotlib
  - pandas
  - pdbfixer
  - parmed
  
  # Workflow management
  - snakemake-minimal >=7.0
  
  # System utilities
  - wget
  - curl
  
  # OpenCL support for GPU acceleration (cross-platform)
  - ocl-icd            # OpenCL ICD loader
  - cuda-opencl-dev    # NVIDIA OpenCL support (optional)
  - intel-opencl-rt    # Intel OpenCL support (optional)
  
  # GPU monitoring and diagnostics  
  - gpustat           # Monitor GPU usage
  
  # Additional tools via pip
  - pip:
    - acpype
    - py3Dmol         # For 3D molecular visualization 